### ISSUE TITLE
Adding missing QGIS infos to output of Reporting tool(?)

### ISSUE THREAD

**Issue by gioman** [planetfederal/qgis-reports-plugin#4]
Compared to the infos that are available in the "about" dialog it seems that the output from the Reports plugin misses the following infos:

geos version
postgresql client version
spatialite version
qwt version
proj.4 version
qscintilla2 version

would be possible to add them, or there is no way to do that?

**Comment by alexbruy** [comment]
As discussed, adding this functionality will lead to adding more dependencies (some of them with C++ code) and increasing maintenance complexity without any considerable improvements.
